### ISSUE TITLE
feat: 라우팅 및 디렉토리 구조 확립

### ISSUE THREAD

**Issue by Goonco** [team-crews/crews-client#4]
### 🤔 Description

* 라우팅과 인증 & 인가와 관련된 전체적인 구조를 확립한다.
* NextJS app router와 비슷한 방식의 디렉토리 구조를 테스팅해 본다.

### 📌 ToDo

- [x] `Router.js`의 전체적인 구조 설정
- [x] app router 디렉토리 구조 테스트
- [x] 인증 인가 구조 설정

### 💬 Others

* 없음 🙅‍♂️ 구현 상세 내용은 PR에 게시하겠음
